apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-project
  namespace: argocd
spec:
  description: Demo project for nginx applications
  sourceRepos:
  - https://github.com/mdsraihaniqbal1999/argocd-app-config.git
  destinations:
  - namespace: default
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  # Core Kubernetes resources
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: ''
    kind: Pod
  - group: ''
    kind: Endpoints
  - group: ''
    kind: Event
  - group: ''
    kind: ServiceAccount
  # Apps resources (THIS WAS THE KEY MISSING PIECE)
  - group: apps
    kind: Deployment
  - group: apps
    kind: ReplicaSet  # ← This was missing and causing your issue!
  # Networking resources (if you use ingress later)
  - group: networking.k8s.io
    kind: Ingress
  - group: networking.k8s.io
    kind: NetworkPolicy
  # Autoscaling (if you use HPA later)
  - group: autoscaling
    kind: HorizontalPodAutoscaler
